name: Go

on:
  [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install tools
      run: make install-tools

    - name: Build
      run: GOFLAGS=-v make build

    - name: Lint
      run: make lint

    - name: Test
      run: GOFLAGS=-v make test